version: '3'
services:
    db: 
      image: mysql:8.0.23
      container_name: mysql
      ports:
          - 3306:3306
      volumes:
          - mysql_volume:/var/lib/mysql
      environment:
        MYSQL_DATABASE: myFit
        MYSQL_ROOT_PASSWORD: 42424242
        MYSQL_USER: vsyveniu
        MYSQL_PASSWORD: 42424242
      restart: always
    phpmyadmin:
      image: phpmyadmin:latest
      container_name: phpmyadmin
      ports: 
        - 3307:80
      depends_on: 
        - db
      restart: always
      environment:
        PMA_HOST: db
        MYSQL_ROOT_PASSWORD: 42424242
        MYSQL_USER: vsyveniu
        MYSQL_PASSWORD: 42424242
    mongodb:
      image: mongo:3.6.22
      container_name: mongo
      ports:
        - 3308:27017
      environment:
        MONGO_INITDB_ROOT_USERNAME: vsyveniu
        MONGO_INITDB_ROOT_PASSWORD: 42424242
        MONGO_INITDB_DATABASE: myfit
      restart: always
      volumes:
        - mongo_volume:/data/db   
    app:
      build: 
        context: .
      container_name: myfitapi
      init: true
      ports:
        - 3000:3000
      environment:
        MYSQL_HOST: db
      volumes:
        - .:/src/myFitApi/ 
        - nodemodules:/src/myFitApi/node_modules 
      restart: always
      depends_on: 
        - db
        - mongodb
      command: npm run start
volumes: 
  nodemodules: {}
  mysql_volume: {}
  mongo_volume: {}
   

